name: weather_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  go_router: 14.6.3
  chopper: 7.4.0
  signals: 6.0.2
  injectable: 2.5.0
  get_it: 8.0.3
  gap: 3.0.1
  json_annotation: 4.9.0
  freezed_annotation: 2.4.4
  dartz: 0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: 2.4.11
  injectable_generator: 2.6.2
  json_serializable: 6.8.0
  freezed: 2.5.2

flutter:

  uses-material-design: true
